title: Multi-Radical Kanji Search (WTK-Search)
author: sschmidTU
url: https://sschmidtu.github.io/mr-kanji-search-wtk/
description: "Search Kanji using WK radicals or RTK names. Type 'arrow mouth' to find çŸ¥, for example."
version: "1.4.6.11"
permalink: /:title/

exclude:
 - README.md
 - CNAME

gems:
 - jekyll-redirect-from
