title: Multi-Radical Kanji Search (WTK)
author: sschmidTU
url: https://sschmidtu.github.io/wtk-fork/
description: "Multi-Radical Kanji Search (WTK). Search engine using multiple Wanikani radicals, RTK primitives (elements) or kanji meanings."
version: "1.3.5.14"

permalink: /:title/

exclude:
 - README.md
 - CNAME

gems:
 - jekyll-redirect-from
