title: Multi-Radical Kanji Search (WTK)
author: anon
url: https://sschmidtu.github.io/wtk-fork/
description: "Multi-Radical Kanji Search (WTK) - prototype. https://github.com/sschmidTU/mr-kanji-search-wtk"
version: "1.3.0.7"

permalink: /:title/

exclude:
 - README.md
 - CNAME

gems:
 - jekyll-redirect-from
