title: Multi-Radical Kanji Search (WTK)
author: sschmidTU
url: https://sschmidtu.github.io/wtk-fork/
description: "Search Kanji using WK radicals or RTK names. Type 'arrow mouth' to find çŸ¥, for example."
version: "1.4.4.0"
permalink: /:title/

exclude:
 - README.md
 - CNAME

gems:
 - jekyll-redirect-from
